### ISSUE TITLE
Pull Request Lab Issue

### ISSUE THREAD

**Issue by sdurmic** [hunter-classes/spring-2021-135-lab-07-melkadze#5]
Hey! I would like to add support for single line if statements that don't have curly brackets.

**Comment by melkadze** [comment]
Sure, sounds good!

**Comment by sdurmic** [comment]
Hey, so I'm having trouble with adding support for if statements. So I decided to add comments to your removeLeadingSpaces() and countChar() instead. Is that fine?

**Comment by melkadze** [comment]
Yeah, of course

**Comment by melkadze** [comment]
Merged relevant pull request
